### ISSUE TITLE
Detecting @deprecated annotations

### ISSUE THREAD

**Issue by juliangamble** [lukehutch/fast-classpath-scanner#102]
My questions is: **Are `@deprecated` annotations special - or is my code wrong?**

```

package util;

import io.github.lukehutch.fastclasspathscanner.FastClasspathScanner;
import io.github.lukehutch.fastclasspathscanner.matchprocessor.ClassAnnotationMatchProcessor;

public class AnnotationScanTest {


    public static void main(String args[]) throws ClassNotFoundException {


        new FastClasspathScanner("com")
                // Optional, in case you want to debug any issues with scanning.
                // Add this right after the constructor to maximize the amount of log info.
                .verbose()
                // Add a MatchProcessor ("Mechanism 1")
                .matchClassesWithAnnotation(Deprecated.class, new ClassAnnotationMatchProcessor() {
                    @Override
                    public void processMatch(Class<?> matchingClass) {
                        System.out.println("Matching annotation: " + matchingClass);
                    }
                })
                // Actually perform the scan (nothing will happen without this call)
                .scan();
    }

}
```

**Comment by lukehutch** [comment]
Works for me, I just tested your code -- but realize that

.matchClassesWithAnnotation(Deprecated.class, ...)


matches class annotations, not method annotations. To match method
annotations, use


.matchClassesWithMethodAnnotation(Deprecated.class, ...)


I just tested this too, and this also works for me.

If you still can't get it working, please open a bug with a minimal
complete testcase attached so I can replicate your environment as closely
as possible. Thanks!

**Comment by lukehutch** [comment]
Works for me, I just tested your code -- but realize that

```java
    .matchClassesWithAnnotation(Deprecated.class, ...)
```

matches class annotations, not method annotations. To match method
annotations, use

```java
    .matchClassesWithMethodAnnotation(Deprecated.class, ...)
```

I just tested this too, and this also works for me.

If you still can't get it working, please attach a minimal complete testcase attached so I can replicate your environment as closely as possible. Thanks!

**Comment by juliangamble** [comment]
I wanted to detect Classes marked deprecated - and it wasn't matching anything. Does the first version of the code work for you?

**Comment by lukehutch** [comment]
@juliangamble yes, it does work for me -- see the test I just committed. What was wrong?
