### ISSUE TITLE
folder src/main/resources missing

### ISSUE THREAD

**Issue by rryi** [lukehutch/fast-classpath-scanner#110]
I downloaded your zip and tried an import to eclipse. Project is broken due to referenced but missing folder src/main/resources, see screenshot

![eclipse-error](https://cloud.githubusercontent.com/assets/26365322/23834746/db3eea32-075b-11e7-9848-e6540d13991c.jpg)

**Comment by lukehutch** [comment]
@rryi thanks for the report. Interesting, I missed this because I still had this empty directory in my project, and git doesn't check in directories, only directory content.

This should be fixed, can you please verify?

**Comment by rryi** [comment]
@lukehutch 
I checked it, now eclipse project is imported w/o error from downloaded and unpacked ZIP archive.
Thanks for fixing so fast.

**Comment by lukehutch** [comment]
Great, thank you for your report.
