### ISSUE TITLE
getMethodInfo throws IllegalArgumentException despite being enabled

### ISSUE THREAD

**Issue by denDAY04** [lukehutch/fast-classpath-scanner#116]
Despite having clearly enabled method staccing with FastClasspathScanner#enableMethodInfo(), it still throws the following exception when I try and extract method information:
`Exception in thread "main" java.lang.IllegalArgumentException: Cannot get method info without calling FastClasspathScanner#enableMethodInfo() before starting the scan`

I'm scanning a jar file that's being loaded into the classpath through an URLClassLoader, then simply printing out the classes and their methods which were found. The code is given below. I simply cannot figure out why it throws this error when the method scanning is clearly enabled, and I've tried moving around the sequence of the chained spec calls, to no success.

    public static JarParser parse(File jarFile) throws FileNotFoundException {        
        if (jarFile == null) {
            return null;
        }

        URLClassLoader loader;
        try {
            URL[] fileUrls = new URL[] {jarFile.toURI().toURL()};
            loader = new URLClassLoader (fileUrls, JarParser.class.getClassLoader());
        } catch (MalformedURLException e) {
            e.printStackTrace();
            throw new FileNotFoundException(jarFile.getAbsolutePath());
        }

        String scanPattern = String.format("jar:%s,-org.qpd", jarFile.getName());
        Map<String, ClassInfo> classInfoMap = new FastClasspathScanner(scanPattern.split(","))
                .enableMethodInfo()
                .strictWhitelist()
                .verbose()
                .overrideClassLoaders(loader)
                .scan()
                .getClassNameToClassInfo();

        classInfoMap.forEach(JarParser::print);

        return null;
    }

    public static void print(String name, ClassInfo info) {
        System.out.println(name);
        info.getMethodInfo().forEach(methodInfo -> System.out.println(String.format("\t\t - %s", methodInfo.getMethodName())));
    }

**Comment by lukehutch** [comment]
@denDAY04 Thanks for reporting this. I was able to duplicate this using your code. Sorry that I didn't test this new feature thoroughly enough before releasing. I just pushed a fix, and your code now works for me with this fix. Please confirm that it also fixes the issue for you. I will push a new version out soon with this change.

**Comment by lukehutch** [comment]
@denDAY04 Released in 2.0.21. I'm pretty confident that this will fix the problem, so I'll close this bug, but please report back to let me know if this version works for you. Thanks again!

**Comment by denDAY04** [comment]
I can confirm that it is working as of 2.0.21, and so does the equivalent scanning of fields (FastClasspathScanner#enableFieldInfo()) which suffered the same problem. Thank you for the quick response. :)

**Comment by lukehutch** [comment]
You're welcome, thanks for testing!
