### ISSUE TITLE
cannot get package annotations when scanning for them

### ISSUE THREAD

**Issue by jjYBdx4IL** [lukehutch/fast-classpath-scanner#120]
The scanner returns the annotated *.package-info 'class', but classRef.getAnnotations() returns an empty array.

Any ideas?

**Comment by lukehutch** [comment]
Interesting. I just added support for package-info recently, and the support is barebones currently. I'll take a look in the next day or two, as I'm traveling currently.

**Comment by jjYBdx4IL** [comment]
ah I probably set the wrong retention policy.

**Comment by lukehutch** [comment]
@jjYBdx4IL OK, please confirm whether it is working once you have the correct retention policy.
