### ISSUE TITLE
Stop recursively scanning one classpath element when the root of another classpath element is encountered

### ISSUE THREAD

**Issue by lukehutch** [lukehutch/fast-classpath-scanner#127]
If a classloader returns two classpath elements where one is a prefix of the other, e.g. `/path/to/lib.jar` and `/path/to/lib.jar!/WEB-INF/classes`, recursive scanning of the ancestral path should stop when it reaches the descendant path, otherwise scanning is duplicated, and for one of the duplicates, classfiles are at the wrong location relative to the classpath element root. (Reported by @DavyDeDurpel)

**Comment by lukehutch** [comment]
@DavyDeDurpel any chance you could please test the latest master version to see if this fixes those log messages you were seeing about classes not being properly located relative to the classpath root? (The classes should only be scanned once now, from the innermost classpath element.)

**Comment by DavyDeDurpel** [comment]
Works like a charm.  It seems a lot faster also.  Difficult to say though as I never really timed it but   
you might need to rename it to **faster-classpath-scanner** :-)

**Comment by lukehutch** [comment]
@DavyDeDurpel :-) Thanks for testing. For jars where both the root of the jar and a subdirectory like `WEB-INF/classes` are both on the classpath, classpath scanning will be up to twice as fast. (I don't know how common this situation is, but that's a big win! Thanks for pointing this out.)
