### ISSUE TITLE
Websphere ClassLoader support is incomplete

### ISSUE THREAD

**Issue by lukehutch** [lukehutch/fast-classpath-scanner#130]
As [reported by Mahesh Boggala](https://groups.google.com/forum/#!topic/fastclasspathscanner-users/GppYcPjkclk) on the mailing list, FCS is not able to handle some of the WebSphere ClassLoaders:

```
com.ibm.ws.bootstrap.ExtClassLoader
com.ibm.ws.classloader.ProtectionClassLoader
com.ibm.ws.classloader.CompoundClassLoader
```

The following also appears in the log as not handled -- I assume this is the ClassLoader of the launch environment?:

```
org.eclipse.osgi.internal.baseadaptor.DefaultClassLoader
```

@RaimondKempees, you helped with the Websphere Liberty ClassLoaderHandler, any chance you could please help get these working too? I am traveling for the next 3 weeks (and additionally have no experience with, or knowledge of, WebSphere, or OSGi either...).

The logs associated with Mahesh's bug report are in the mailing list thread linked above.

**Comment by RaimondKempees** [comment]
@lukehutch I'll have a look.

**Comment by lukehutch** [comment]
@RaimondKempees thanks. After this bug report was opened, support for `com.ibm.ws.classloader.CompoundClassLoader` was added by @sbespalov in 2.4.5.

The other three named ClassLoaders probably also should be supported at some point, but it is possible the `CompoundClassLoader` is the only one needed for user-provided classes, so we have a partial fix in place.

**Comment by RaimondKempees** [comment]
@lukehutch, Mahesh is using Websphere Traditional, which has a whole different class loading setup and classes. @sbespalov already fixed that, so it's a matter of releasing 2.4.6. I did add support for both the ProtectionClassloader and the ExtClassLoader here: https://github.com/lukehutch/fast-classpath-scanner/pull/134

**Comment by RaimondKempees** [comment]
Agreed!

**Comment by lukehutch** [comment]
Should be fixed now. Thank you, @RaimondKempees.
