### ISSUE TITLE
Support different ClassLoader parent delegation modes

### ISSUE THREAD

**Issue by lukehutch** [lukehutch/fast-classpath-scanner#131]
WebSphere (and probably other runtime environments) supports different types of ClassLoader delegation modes, e.g.:

```
com.ibm.ws.classloader.CompoundClassLoader@ed1fe264[war:rb-webservice-ear/rbwebservice.war]
   Local ClassPath: C:\workspace\.metadata\.plugins\ [...]
   Parent: com.ibm.ws.classloader.CompoundClassLoader@d2831cb0[PF][app:rb-webservice-ear]
   Delegation Mode: PARENT_FIRST
```

Currently, we default to PARENT_FIRST for all ClassLoaders. Instead, ClassLoaderHandlers should have a method added that defaults to PARENT_FIRST, but allows a different value to be given as an override. (What other modes does WebSphere support?)

Then ClasspathFinder should respect this setting when adding paths from parent ClassLoaders.

**Comment by lukehutch** [comment]
[More info on Parent_first vs. Parent_last](http://www-01.ibm.com/support/docview.wss?uid=swg27023549&aid=1).

**Comment by lukehutch** [comment]
@RaimondKempees I added support to `ClassLoaderHandler` to support parent delegation mode for Websphere, but I can't find the source for the `ClassLoaders` in question, so I don't know how to read the delegation mode, and I don't know anything about setting up WebSphere. Could I get your assistance to get this working, please? See the latest checkin to master. You just need to override the default value of `PARENT_FIRST` in `WebsphereLibertyClassLoaderHandler.java` and `WebsphereLibertyClassLoaderHandler.java` with whatever the correct field is for a given WebSphere ClassLoader. Thanks!

**Comment by lukehutch** [comment]
@RaimondKempees I tried firing up a Hello World program in WebSphere (traditional and Liberty), and was amazed at how complex it was to set up. I gave up after a while, so I never managed to dig into the classloaders to see how to extract the delegation mode. If you can point me to some small WebSphere test project I can fire up easily, or if you have time to look into fetching the delegation mode in the different WebSphere classloaders, I would really appreciate it! Thanks!

**Comment by RaimondKempees** [comment]
Hi Luke,

Am traveling these few weeks, so will look somewhere in October!

**Comment by lukehutch** [comment]
OK, no rush, thank you!

**Comment by lukehutch** [comment]
[Liberty is now opensourced](https://github.com/OpenLiberty/open-liberty). (I don't know if this also includes Websphere Traditional, but I think not?)

There's a hard-coded parent-first delegation order in [AppClassLoader](https://github.com/OpenLiberty/open-liberty/blob/master/dev/com.ibm.ws.classloading/src/com/ibm/ws/classloading/internal/AppClassLoader.java), but I believe there are other classloaders somewhere that I haven't found yet...

**Comment by GedMarc** [comment]
WebSphere shouldn't be used for production in any case, and in most instances is frowned upon for usage JDK6 and up. It is for legacy software only and should not be used for any new development performed in this decade. The base language is JDK5 and is not backwards compatible from JRE8.
WebLogic also fits in this bucket and was chucked out for Glassfish.

If you can - switch to an actual EE server developed built, I dunno, in the past 10 years (Payara, Glassfish, Wildfly, TomEE etc), if you can't, It is in my opinion you should not use this software and should look at legacy solutions that provide the same sort of functionality.

**Comment by lukehutch** [comment]
@GedMarc good info, I don't know anything about any of these containers, so thanks, I'll close this bug. If you're feeling ambitious, it would be great if you could see if there are any classloaders in the more modern environments that you mentioned that aren't properly supported yet.
