### ISSUE TITLE
How to  get the superclasses class info after the scan.

### ISSUE THREAD

**Issue by febielgiva** [lukehutch/fast-classpath-scanner#138]
My code would be

`                ScanResult scanResult = new FastClasspathScanner(ProcName.class.getPackage().getName()).ignoreFieldVisibility().enableFieldInfo().enableFieldAnnotationIndexing().enableFieldTypeIndexing().ignoreMethodVisibility().enableMethodInfo().enableMethodAnnotationIndexing().ignoreParentClassLoaders().verbose().scan();

                  Map<String, ClassInfo> classNameToClassInfo = this.scanResult.getClassNameToClassInfo();
                 ClassInfo classInfo = this.classNameToClassInfo.get(Account.class.getName());
		 // gets all the superClasses fieldInfos
		 (classInfo.getSuperclasses()).forEach(superClass -> {
		 System.out.println(superClass + " " + superClass.getFieldInfo().size());
		 });`

I am not able to get the list of fieldInfo for the all possible superclasses

**Comment by lukehutch** [comment]
Are the superclasses in the same package as `ProcName`, or one of its subpackages?

**Comment by lukehutch** [comment]
(if not, then they are "external classes", meaning external to the whitelist, so those superclasses are known by name only, they are not scanned)

**Comment by febielgiva** [comment]
its present in the classNameToClassInfo map but with null value in List<FieldInfo> field

**Comment by febielgiva** [comment]
Thanks for the quick response. I think its because of the abstract class.  okay Let me draft my question like this . Does the abstract class when scanned will give the fieldInfo and MethodInfo?

**Comment by lukehutch** [comment]
@febielgiva Abstract classes should not be treated differently. Please see the test I just checked in. Can you please try to modify this test to trigger the behavior you are seeing?

**Comment by lukehutch** [comment]
(The test passes for me.)

**Comment by febielgiva** [comment]
okay thank you . i will look into my code again . I might have missed something. Thank you for your time

**Comment by lukehutch** [comment]
@febielgiva Almost certainly what is happening is that there is a superclass of `Account` that is not in the whitelisted package `ProcName.class.getPackage().getName()` or a sub-package.

**Comment by febielgiva** [comment]
ya that is the issue . Thanks for the time . Your lib is very useful . Keep up the good work :)

**Comment by febielgiva** [comment]
@lukehutch  is there any functions to get all the package name in a project in your lib ?

**Comment by febielgiva** [comment]
I got it https://github.com/lukehutch/fast-classpath-scanner/wiki/2.-Constructor this link is usefull . Thank you .

**Comment by lukehutch** [comment]
@febielgiva glad you figured it out. Thanks for reporting anyway. 

As far as listing all package names, what I would probably do is [list all classes](https://github.com/lukehutch/fast-classpath-scanner/wiki/3.8.-Enumerating-all-classes-on-the-classpath), and then extract the package name from each class name, and put the package names into a `Set`.
