### ISSUE TITLE
java.io.IOException: Could not read whole file 

### ISSUE THREAD

**Issue by GedMarc** [lukehutch/fast-classpath-scanner#145]
Occurs when loading from Wildfly 10 with any inner jar on the VFS (lib)

12:10:07,238 ERROR [stderr] (MSC service thread 1-4) 2017-10-02T12:10:05.543+0200	FastClasspathScanner	-- Exception while opening file jar:file:/C:/java/devstudio/runtimes/jboss-eap/standalone/tmp/vfs/deployment/deployment231e896dadb0dd92/hazelcast-3.8.3.jar-c36cfdefd452a91d/hazelcast-3.8.3.jar!/hazelcast-full-example.xml
12:10:07,239 ERROR [stderr] (MSC service thread 1-4) 2017-10-02T12:10:05.543+0200	FastClasspathScanner	---- java.io.IOException: Could not read whole file
12:10:07,240 ERROR [stderr] (MSC service thread 1-4) 2017-10-02T12:10:05.543+0200	FastClasspathScanner	---- 	at io.github.lukehutch.fastclasspathscanner.scanner.ScanSpec.readAllBytes(ScanSpec.java:1506)
12:10:07,241 ERROR [stderr] (MSC service thread 1-4) 2017-10-02T12:10:05.543+0200	FastClasspathScanner	---- 	at io.github.lukehutch.fastclasspathscanner.scanner.ScanSpec.access$300(ScanSpec.java:72)
12:10:07,243 ERROR [stderr] (MSC service thread 1-4) 2017-10-02T12:10:05.543+0200	FastClasspathScanner	---- 	at io.github.lukehutch.fastclasspathscanner.scanner.ScanSpec$15.processMatch(ScanSpec.java:1551)
12:10:07,243 ERROR [stderr] (MSC service thread 1-4) 2017-10-02T12:10:05.543+0200	FastClasspathScanner	---- 	at io.github.lukehutch.fastclasspathscanner.scanner.ClasspathElementZip.openInputStreamAndProcessFileMatch(ClasspathElementZip.java:319)
12:10:07,244 ERROR [stderr] (MSC service thread 1-4) 2017-10-02T12:10:05.543+0200	FastClasspathScanner	---- 	at io.github.lukehutch.fastclasspathscanner.scanner.ClasspathElement.callFileMatchProcessors(ClasspathElement.java:314)
12:10:07,245 ERROR [stderr] (MSC service thread 1-4) 2017-10-02T12:10:05.543+0200	FastClasspathScanner	---- 	at io.github.lukehutch.fastclasspathscanner.scanner.ScanSpec.callMatchProcessors(ScanSpec.java:497)
12:10:07,246 ERROR [stderr] (MSC service thread 1-4) 2017-10-02T12:10:05.543+0200	FastClasspathScanner	---- 	at io.github.lukehutch.fastclasspathscanner.FastClasspathScanner.scan(FastClasspathScanner.java:1379)
12:10:07,247 ERROR [stderr] (MSC service thread 1-4) 2017-10-02T12:10:05.543+0200	FastClasspathScanner	---- 	at io.github.lukehutch.fastclasspathscanner.FastClasspathScanner.scan(FastClasspathScanner.java:1440)
12:10:07,248 ERROR [stderr] (MSC service thread 1-4) 2017-10-02T12:10:05.543+0200	FastClasspathScanner	---- 	at io.github.lukehutch.fastclasspathscanner.FastClasspathScanner.scan(FastClasspathScanner.java:1463)

**Comment by lukehutch** [comment]
Hi, thanks for this report. Can you please test the master version, with the latest push? If it still crashes, please can you attach the whole log? (The latest version logs the actual and expected filesize, and fixes an issue with how read() was being called, but I also want to see the log lines about decompressing temporary files.) Thank you!

**Comment by lukehutch** [comment]
There was definitely a bug in how `read()` was being called. I don't know if it will fix your particular issue, but it would probably impact somebody eventually, so I pushed out version 2.7.1 with the latest change. It may be easier for you to try 2.7.1 rather than have to build your own version from git master. Please let me know if you still see the problem.

**Comment by lukehutch** [comment]
@GedMarc PS if version 2.7.1 or later doesn't fix this issue, can you please provide a small test project that demonstrates the issue? I tried and failed to get WildFly up and running once before for another issue.

**Comment by GedMarc** [comment]
Looking good :) Let's close this guy off!

Fantastic Library Luke!

**Comment by lukehutch** [comment]
@GedMarc Thanks, glad it fixed the problem for you!
