### ISSUE TITLE
how to tell a ClassInfo's access level(public/package/private) or it's a inner class?

### ISSUE THREAD

**Issue by dantesun** [lukehutch/fast-classpath-scanner#148]
It seems there's no way to tell if a ClassInfo is public or not? And also no way to find out if a class is a innner class or has inner classes.

**Comment by lukehutch** [comment]
ClassInfo is public, because it is exposed in the public API.

I think you can just look in the class name for a dollar sign? Only inner classes can have dollar signs.

To detect if a class has inner classes, see if its name, followed by a dollar sign, is a string prefix of another class name. (Look at the class names following it in a sorted list of all class names.)

Does that work?

**Comment by dantesun** [comment]
I am sorry but what I meant "public", I mean the java class represented by a ClassInfo. I want to know is the access level of a class/interface/annotations whose name is  ClassInfo.getName()

**Comment by GedMarc** [comment]
@dantesun is getClass().getModifiers() == Modifier.PUBLIC not viable?

**Comment by dantesun** [comment]
@GedMarc do you mean java.lang.Object.getClass().getModifiers() ? What I want is get the class modifiers without actually loading a class through classloader. The modifiers information can be extracted from .class file. But `io.github.lukehutch.fastclasspathscanner.scanner.ClassInfo` doesn't have class modifiers information.

**Comment by lukehutch** [comment]
@GedMarc I think @dantesun wants to do this without loading classes. Modifiers are now supported using `ClassInfo#getClassModifiers()` in commit fc3613aa493d48f8893c24e1f377fa43201a9537. I also modified `ClassInfo#toString()` to include the modifiers. I will push this out as 2.8.0.

As far as detecting nesting of classes -- I'm working on it. It's quite complicated to parse this out of the classfiles.

**Comment by lukehutch** [comment]
@dantesun Class containment info is available in dddfd2bca74a3865e266b0b40ba90e7c4a3ecb82.

**Comment by lukehutch** [comment]
Both features are released in version 2.8.0.

https://github.com/lukehutch/fast-classpath-scanner/releases/tag/fast-classpath-scanner-2.8.0
