### ISSUE TITLE
Release Notes Inconsistency

### ISSUE THREAD

**Issue by GedMarc** [lukehutch/fast-classpath-scanner#157]
Just a small thing with regards to the release notes for 2.9.x

#154 relates to Oracles WebLogic framework EE6 and not JBoss
#156 relates to JBoss EAP 7+ and WildFly 10+ EE7, as well as Payara 4&5 and Glassfish 4,5A+ EE 7&8, JDK 8 And JDK9  
I'm still writing the test cases but I've tested my scenarios..

Kind Regards,

**Comment by lukehutch** [comment]
Sorry, I wrote those notes hastily while my flight was boarding (and didn't have that info on which versions were affected -- thank you for that!). 

However, #156 has nothing to do with JBoss/Wildfly etc. per se, it is about ignoring exceptions. Maybe you mean #150? But that was already merged in a previous release. Or did I miss something else in the release notes?

I could actually use your help here -- I know very little about any of these runtime environments, so I don't even know how to summarize which runtime environment releases the different [`ClassLoaderHandler`s](https://github.com/lukehutch/fast-classpath-scanner/tree/master/src/main/java/io/github/lukehutch/fastclasspathscanner/classloaderhandler) work with. Any chance you could please suggest some further detail for the following Wiki section?:

https://github.com/lukehutch/fast-classpath-scanner/wiki#classpath-mechanisms-and-classloaders-handled-by-fastclasspathscanner

(I don't want to add too much specific version information, if supporting a given environment will likely work across many versions, but in some cases version numbers would be appropriate.)

Thanks for working on those test cases. Let me know if you run into any problems.

**Comment by GedMarc** [comment]
You and I both :) Cell typing waiting for my flight lol!

Will take a look!

**Comment by GedMarc** [comment]
Looks like #145 instead of 156,

**Comment by lukehutch** [comment]
Thanks for the followup.
