### ISSUE TITLE
Not incrementing 'i' in AnnotationInfo.getUniqueAnnotationNamesSorted()

### ISSUE THREAD

**Issue by mrlambeth** [lukehutch/fast-classpath-scanner#158]
![screen shot 2017-11-13 at 3 59 13 pm](https://user-images.githubusercontent.com/6352551/32748899-a514b2f6-c88b-11e7-9368-6c727a7bb1b1.png)

**Comment by lukehutch** [comment]
Thanks, good catch, sorry about that. Fixed and released in version 2.9.2.
