### ISSUE TITLE
Add ability to whitelist a canonical path as a jar

### ISSUE THREAD

**Issue by facboy** [lukehutch/fast-classpath-scanner#166]
I have a problem when running Flink under Yarn, it ships the jars to the task managers in a blob store.  These show up on the classpath as files without any extension (they have a base64 name based on their key in the blob store).  fast-classpath-scanner ignores these jars because they don't end with an appropriate extension.  unfortunately i don't have any control over how these are named.

is it possible to have a 'whitelist' or something similar that would allow me to say, 'this is definitely a jar, please treat it as such'?

**Comment by lukehutch** [comment]
Thanks for the report. Fixed in version 2.9.5, just released. The changes make FCS no longer rely on the file extension: if a file is encountered on the classpath, an attempt is made to open it as a zipfile, regardless of the extension. I added a unit test, so this should work for you, but please let me know if it doesn't.

**Comment by GedMarc** [comment]
This is great, will help a lot with sars, hars and the likes. 
is there a performance knock? Or a flag to disable the function? :)

**Comment by lukehutch** [comment]
There are so many *ars... at last count, I had jar, zip, war, car, ear, sar, har, par and wsjar...

No, there should be no performance impact. FCS just no longer early-rejects classpath elements without the right sort of filename extension.

Both zipfiles and directories can tell if a given relative path is a directory or file (or doesn't exist). I just assume that if a path is provided, and it maps to a file (as opposed to a directory), then it must be a zipfile. During scanning, when FCS tries to open the classpath element, if it's not a zipfile then an exception is thrown by `ZipFile#open()`, causing that classpath element to be skipped.

I think this is better behavior than relying on a file extension whitelist for jars, so I don't think there needs to be a flag to disable this (but correct me if I'm wrong).

One thing that this will preclude is listing non-jar files directly on the classpath (e.g. resource files or default-package classfiles) -- but I think this is not supported by the JRE or any container type anyway.

**Comment by facboy** [comment]
yes it seems to work, thanks for the prompt fix!

**Comment by lukehutch** [comment]
@facboy great, thanks for confirming.
