### ISSUE TITLE
Indeterminate order of scanSpec evaluation can result in missed classes

### ISSUE THREAD

**Issue by badfish69** [lukehutch/fast-classpath-scanner#167]
Due to the way scanSpec evaluates a list of packages, the order in which they are evaluated can be important.

For example, if the scanSpec includes packages that are ancestors of other packages in the spec, it is critical that the earliest ancestor is evaluated first (so a HAS_WHITELISTED_PATH_PREFIX result can be returned), otherwise an ANCESTOR_OF_WHITELISTED_PATH result may be returned resulting in any classes within that specific package getting ignored.

Currently scanSpec uses HashSet to build the lists of whitelisted/blacklisted packages.  This results in an indeterminate order of evaluation when scanning packages.  At the very least, it should probably use LinkedHashSet so the calling code can at least have the option of providing the spec in the correct order, but I suspect the correct fix is for the resulting path lists to be sorted to ensure correct evaluation order regardless of the order in which they are supplied in the spec.

**Comment by badfish69** [comment]
FYI: I've submitted pull request #168 as a demonstration of the issue and also a proposed fix.

**Comment by lukehutch** [comment]
@badfish69 Many thanks for finding this issue, figuring out the (complex) cause, and submitting not just a patch but also a unit test! I'll push this out in a release this evening, probably -- I have another issue I need to fix first.

**Comment by lukehutch** [comment]
Released in 2.10.0.

**Comment by badfish69** [comment]
@lukehutch Thanks for the quick turnaround with the release... means I can use a released version of the package rather than my patched snapshot :-)
