### ISSUE TITLE
scan result improvments

### ISSUE THREAD

**Issue by johnfg10** [lukehutch/fast-classpath-scanner#186]
Hey,
I have a suggestion for the scan result class, it would be useful if we had an equivalent of `getNamesOfClassesWithAnnotationsAnyOf()` for fields and for methods so something similar to `getNamesOfClassesWithFieldAnnotationAnyOf()` and `getNamesOfClassesWithMethodAnnotationAnyOf()`. i think this would be a good feature for certain use cases.
Thanks,
John

**Comment by lukehutch** [comment]
@johnfg10 I agree, these would be good additions. But we would also need `getNamesOfClassesWithMethodParameterAnnotationAnyOf()`, and the `...AllOf()` variants for consistency. There are way too many API calls like this already, and the API has become really unweildy, so what I plan to do is actually build a query API where you can express these sorts of concepts flexibly in a compositional way, something like `scanner.findClassesWhere(Op.fieldNameEquals("name").and(Op.fieldHasAnnotation("Annotation"))` . I haven't started on this, but will hopefully work on this in the next three months or so, and that will be the 3.0 release.

**Comment by lukehutch** [comment]
I'll close this, as it is really subsumed within #111 (API Cleanup). Thanks @johnfg10 for the request!
