### ISSUE TITLE
Matcher classes

### ISSUE THREAD

**Issue by davidmoshal** [lukehutch/fast-classpath-scanner#188]
Not a bug, just a question about how to use matcher classes.
I looked at your three mechanisms, and tried them out,
but I can't see where the 'predicate' for an inclusion or exclusion matcher is set,
the various Single Abstract Method matching classes don't have methods that return boolean.
What am I missing?

**Comment by lukehutch** [comment]
There are some simple predicates included in the API itself, for example you can match just classes that implement a given interface. More complex filters can be added by getting the `ScanResult` returned by the call to `.scan()`, then calling `.getClassNameToClassInfo()` to get a `Map<String, ClassInfo>` for all the classes that matched the top-level filtering, then you can call `.values()` to get a `Collection<ClassInfo>` of class info objects, and you can use standard Java 8+ SAM filtering primitives if you convert that collection to a stream.

As I mentioned in #187, the API will soon be significantly enhanced to support a much richer query syntax that will make a lot of this sort of filtering unnecessary.

**Comment by davidmoshal** [comment]
ok, thanks, I'm calling generate dot file on the scan result, so was hoping to include a matching predicate befare scan() as it's not exactly clear how to generate a dot file from passing the scan result.

**Comment by lukehutch** [comment]
Ah! That's a really good point, you should be able to generate a dot file based on only filtered criteria.

With the current API, it's not possible to do this, unfortunately, but I'll make this work properly in version 3.0, once the new API is ready. 

For now, you can just copy the .dot file generation code in the following class into your own codebase, and adapt it to your needs, so that only the classes that match your criteria are included in the graph:

https://github.com/lukehutch/fast-classpath-scanner/blob/master/src/main/java/io/github/lukehutch/fastclasspathscanner/scanner/ClassGraphBuilder.java#L241

**Comment by davidmoshal** [comment]
yep, that's pretty much what I did, I'm using xdot on linux which regenerates the graphviz file automatically when the dot file changes.
- but, back to my earlier point, why not simply allow a matcher with a predicate before scan,
e.g:

```groovy
// groovy:
String output = new FastClasspathScanner ( "app.model" )
  .strictWhitelist ()
  .ignoreFieldVisibility ()
  .enableFieldTypeIndexing ()
  .match { Class c ->
     return c.name.startsWith('X')
  }
  .scan ()
  .generateClassGraphDotFile ( 9.2f, 8.0f )
```

I guess I'm asking how difficult it would be to simple allow a matching predicate in the chain?

Dave

**Comment by lukehutch** [comment]
Just a heads up -- I will be releasing version 4 of FCS in the next couple of days, and this introduces a new class, `ClassInfoList` (extending `List<ClassInfo>`) which is produced as a result of applying filter criteria. You can now generate a GraphViz graph from any `ClassInfoList`, so you can visualize the result of any filter criteria.

**Comment by davidmoshal** [comment]
Nice!
