### ISSUE TITLE
Not working for packages in a jar file?

### ISSUE THREAD

**Issue by V-ed** [lukehutch/fast-classpath-scanner#194]
Running this library directly in let's say IntelliJ IDEA works as expected, but when running the same code from a jar file, the Exception below is thrown.

```
Exception in thread "[thread_name]" java.lang.NoClassDefFoundError: io/github/lukehutch/fastclasspathscanner/FastClasspathScanner
        at vendor.objects.CommandLinksContainer.<init>(CommandLinksContainer.java:41)
        at app.BotCommandsLinker$1.<init>(BotCommandsLinker.java:14)
        at app.BotCommandsLinker.createLinksContainer(BotCommandsLinker.java:14)
        at vendor.abstracts.CommandsLinker.getContainer(CommandsLinker.java:20)
        at vendor.objects.CommandsRepository.getContainer(CommandsRepository.java:21)
        at app.CommandRouter.run(CommandRouter.java:147)
Caused by: java.lang.ClassNotFoundException: io.github.lukehutch.fastclasspathscanner.FastClasspathScanner
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 6 more
```

Here is the code that runs this issue in a jar file :
```java
ScanResult results = new FastClasspathScanner(linksPackage).strictWhitelist().scan();
		
List<String> classNames = results.getNamesOfAllClasses();
	
List<Class<?>> linkableClasses = results.classNamesToClassRefs(classNames);
	
ArrayList<Link> links = new ArrayList<>();
	
linkableClasses.forEach(linkableClass -> {
		
	if(LinkableCommand.class.isAssignableFrom(linkableClass)){
			
		links.add(new Link((Class<LinkableCommand>)linkableClass));
			
	}
		
});
```

The `.verbose()` does output alot of data in "local mode" (not in a jar file) but no information is thrown (except this error stack) when running from the jar file.

P.S. : _I know that I may not be using the scanner at its full potential (I'm searching for all the classes and then filtering those with the interface `LinkableCommand` while the scanner seems to have ways to do that automatically) but I couldn't get it working._

If you want to to send the `.verbose()` log of the working conditions (again, when not in a jar file), just let me know!

**Comment by lukehutch** [comment]
Hi @V-ed, thanks for the report. This is weird -- where is the exception being thrown? The stacktrace doesn't seem to show the exception being triggered either from the FCS library or from your own code. Can you please do a bit more sleuthing to figure out where this is being triggered in FCS or your code?

This might be due to a packaging error. Are you building the jarfile in IDEA, or Maven, or something else? It looks like the compilation succeeds, and the jar is built, but then not all the classfiles are stored in the right classpath root in the jar, so they can't be linked at runtime.

**Comment by V-ed** [comment]
The Exception is thrown when scanning for classfiles (the first line of my sample code, I should've mentionned it earlier!).

The `src` folder contains the "commands" package which is what I'm trying to find here, and the jar does not have this src folder as it's considered as a source folder (default java project directory).

I'll try to tweak stuff here and there and let you know if something works. Meanwhile, if you wanna see the directory structure we use for our project, you can see it [here](https://github.com/Vhoyon/Discord-Bot/tree/dynamic-command-loading) (it's a project to learn some discord API).

**Comment by lukehutch** [comment]
Please do attach the complete verbose logs, maybe there's something else there that will be helpful...

**Comment by V-ed** [comment]
Well, I feel kinda dumb now.

I rechecked the artifact created by IntelliJ IDEA and the build process wasn't including your FastClasspathScanner library into the jar file.

As you thought, it was indeed a packaging error!

Thanks alot for the quick answer and sorry for making an issue which wasn't cause by your library but rather my lack of knowledge on IntelliJ's artifact building process! Your library is really useful!

**Comment by lukehutch** [comment]
@V-ed no problem at all! I'd rather know about every little thing like this in case it's a bug in FCS. Glad you found the cause!
