### ISSUE TITLE
scan spec help

### ISSUE THREAD

**Issue by alexec** [lukehutch/fast-classpath-scanner#195]
Hi,

I have an application with a very large number of jars and classes. A large amount of start-up time is due to classpath scanning, so I'd like to get exactly the best scan specs possible.

Originally it was a single entry:

* `com.intuit.v4`

I updated it to: 

* "`com.intuit.v4`"
* "`jar:com.v4-sdk-*.jar`"
* "`-dir`

But I'm not sure it is any faster. Any thoughts?

**Comment by lukehutch** [comment]
Hi @alexec,

Please let me know if something like the following speeds up the scanning process:

```java
ScanResult scanResult = new FastClasspathScanner("com.intuit.v4")
    .overrideClasspath(
        new FastClasspathScanner()
            .getUniqueClasspathElements()
            .stream()
            .filter(file -> file.getPath().contains("/com.v4-sdk-"))
            .collect(Collectors.toList()))
    .scan();
```

**Comment by lukehutch** [comment]
@alexec I'll close this issue, but please comment to let me know if the suggested code reduced the scan time, and by how much.
