### ISSUE TITLE
publish to maven center

### ISSUE THREAD

**Issue by hepin1989** [lukehutch/fast-classpath-scanner#2]
currently when I am writing a kryo serializer for akka-remote,I found that I really need something like this.
I want to auto register classes to the kryo.
I currently using something like this:
It not good but works.
```scala
 def subTypeof[T](clazz:Class[T],filter:String => Boolean):Set[Class[_]] = {
    val classPath = ClassPath.from(this.getClass.getClassLoader)
    val allClasses = classPath.getAllClasses
    implicit def imutableSet2ScalaSet[V](input:ImmutableSet[V]):Set[V] = {
      val itr = input.iterator()
      var set = Set.empty[V]
      while (itr.hasNext){
        set += itr.next()
      }
      set
    }
    allClasses.filter(classInfo => filter(classInfo.getName)).map(_.load()).filter(clazz.isAssignableFrom)
  }
```
I think your way or the classindex way will be nice https://github.com/atteo/classindex I will not going to use ```Reflections```,so many addition dependencies.
so how about publish to the maven center?

**Comment by lukehutch** [comment]
It's in Sonatype now, on its way to Maven Central. Wow, Maven is a nightmare. Thanks for the encouragement to get this done.

**Comment by hepin1989** [comment]
very thanks for you done this too.

**Comment by hepin1989** [comment]
seems like haven't sync to maven center
search here ,not found :http://mvnrepository.com/

**Comment by lukehutch** [comment]
Yes, it's still waiting to be approved by the Sonatype guys, but the 1.0.0
repository has been released on Sonatype, so all that is required is for
Sonatype to set up sync to Maven Central. Hopefully that will happen on
Monday.

**Comment by hepin1989** [comment]
yes,you have to register first...thank you very much.

**Comment by lukehutch** [comment]
I'm registered, the request is filed, and I have been working with them on
this. They just have to complete the last step and push the button.

**Comment by hepin1989** [comment]
you could try this https://bintray.com/ :P.
thank you again
