### ISSUE TITLE
ReflectionUtils to support Java "ea" versioning scheme maybe?

### ISSUE THREAD

**Issue by zhgzhg** [lukehutch/fast-classpath-scanner#201]
Greetings,

On FCP 3.0.3 I've seen that the ReflectionUtils logic for "JAVA_VERSION_IS_9_PLUS" is not handling early access versioning like for e.g. "11-ea" - more info here [http://openjdk.java.net/jeps/223)](http://openjdk.java.net/jeps/223) .
In result for such version I get java.lang.NumberFormatException: For input string: "11-ea"

Since Java is expected to evolve much faster do you think it is a good idea to support the early access versioning scheme?

Regards,
zhgzhg

**Comment by lukehutch** [comment]
@zhgzhg Thank you, I wasn't checking for the '-' character. I made this more generic so any non-numeric character can be used to break version numbers. The fix will be in the next release, and it is checked into master now, so you can build your own jar if you need this fixed ASAP.
