### ISSUE TITLE
Configure Travis to test with Java 11 and/or EA

### ISSUE THREAD

**Issue by seanf** [lukehutch/fast-classpath-scanner#203]
Travis now supports testing with newer versions of the JDK (Oracle or OpenJDK)

You can see most of the new jdk names in the matrix here: https://github.com/BrynCooke/cdi-unit/blob/master/.travis.yml

There are some test failures on 11/EA here, but I haven't worked out if they're a problem with FCS or CDI-Unit: https://travis-ci.org/BrynCooke/cdi-unit/builds/395975288 Might just be https://github.com/lukehutch/fast-classpath-scanner/issues/201

**Comment by seanf** [comment]
Created #204

**Comment by lukehutch** [comment]
Hi, thanks, please test with the master version. I have been working pretty intensively on FastClasspathScanner over the last couple of weeks, but I just finished the work tonight, and everything should be stable again.

**Comment by lukehutch** [comment]
PS let me know if you get any failures. Thanks for the pull request!
