### ISSUE TITLE
'Master' build broken by "Add JSON deserializer"

### ISSUE THREAD

**Issue by seanf** [lukehutch/fast-classpath-scanner#205]
Looks like compilation was broken by commit https://github.com/lukehutch/fast-classpath-scanner/commit/e1abae353a9671f9910136e07a69391fe982b62b

See https://travis-ci.org/lukehutch/fast-classpath-scanner/builds/395423627#L1557

**Comment by lukehutch** [comment]
Yes, sorry, it's fixed now. Thanks for reporting.
