### ISSUE TITLE
Include only tools.jar as "system jar", not the entire jre/../lib folder

### ISSUE THREAD

**Issue by gcristescu** [lukehutch/fast-classpath-scanner#206]
Hello,

I have a folder structure as below:
- root
    - jre
         - JRE files ("java.home" points to this)
    - lib
        - my jars

The current logic within JREUtils is seeing all my jars within this "lib" folder as "system jars":

```
            if (javaHomeFile.getName().equals("jre")) {
                // Handle jre/../lib/tools.jar
                final File parent = javaHomeFile.getParentFile();
                if (parent != null) {
                    final File parentLibFile = new File(parent, "lib");
                    addJREPath(parentLibFile, jrePathsSet);
                }
            }
```
Would it be possible - and sensible - to only regard "tools.jar" as a system jar, instead of the entire "lib" folder? 

This was tested with version 3.1.0.

**Comment by lukehutch** [comment]
Hi @gcristescu -- thanks for pointing this out, and thanks for tracking down the issue. I'm not very familiar with the use of `lib/` for installing user jars (I know `ext/` is a common place for putting them), but this request to exclude only specific jars in `lib/` sounds reasonable. Along with `tools.jar` and `rt.jar`, are there any others that might need excluding? I don't have Windows or Mac OS X, and I know some Java installations are very different from OpenJDK as far as where they put system jars. The current system could be made more robust for sure. Can you suggest a set of robust rules that should work across a range of JDK installation types, for identifying system jars?

**Comment by lukehutch** [comment]
In the Fedora JDK 1.8 installation (java-1.8.0-openjdk-1.8.0.171-4.b10.fc28.x86_64), I see `dt.jar`, `jconsole.jar`, `sa-jdi.jar` and `tools.jar`. I don't even know what most of these are :-) In the latest Oracle JDK 1.8 installation all of those are present, as well as `ant-javafx.jar`, `javafx-mx.jar`, and `packager.jar`.

It might be possible to build a database of what jars are installed in those directories across major JDK versions on the major operating systems. It seems though that whitelisting `lib/` in general may not be the right thing to do, because JDK and JRE installations could easily include a big jar in there with an unusual name or something, and that would slow down scanning for all users on those installations who are not interested in scanning system jars. 

Maybe I should add a configuration option to specifically enable scanning of named jars in `lib/` and `ext/`?

**Comment by gcristescu** [comment]
Thank you for the lightning-fast response.

As we discuss about it, I am also starting to hesitate, and to share your opinion that fully whitelisting `lib/` might have too wide unknown implications.

So, as you say, perhaps a configuration option that would whitelist a package or a jar, but also override any blacklist, even the one regarding "system jars". Something like:

`"!my.jar"` - whitelist a specific jar, even if inside a JRE folder
`"!*.jar"` - same as above, but with wildcard
`"!*/lib/*.jar"` - I guess this is what would solve my particular problem

**Comment by gcristescu** [comment]
Another (perhaps less exotic) possibility: offer support for wildcards for jars. The following would include system jar folders, but exclude` jre/lib`, `jre/ext`, and `tools.jar`.

`new FastClasspathScanner("!!", "-jar:jre/lib/*.jar", "-jar:jre/lib/ext/*.jar", "-jar:lib/tools.jar")`

**Comment by lukehutch** [comment]
Something like that should work. I need to make the whole whitelisting thing more flexible and simpler, which I will try to do in the next API redesign (the API is way too complex already, and it will get more complex once I start adding options for whitelisting and blacklisting Java modules). However, for now, maybe I can add scan spec prefixes `lib:` and `ext:`, e.g. `new FastClasspathScanner("lib:xyz.jar", "com.xyz.pkg");` ?  That would whitelist a specific package in `lib/`.

**Comment by lukehutch** [comment]
@gcristescu Please try the master version. You should be able to whitelist your jar name in the scan spec using `"lib:yourjarname.jar"`. You can also whitelist jars in `ext/` in a similar way, using `"ext:yourjarname.jar"`.

**Comment by lukehutch** [comment]
@gcristescu I made a few more changes. The latest master version is released as 3.1.3 -- please test with that version, and let me know if it works for you. Thanks!

**Comment by gcristescu** [comment]
@lukehutch `"lib:yourjarname.jar"` does not seem to have any effect; now, please bear with me (apologies if I have overlooked anything): in JarUtils, you added JRE_LIB_JARS and JRE_EXT_JARS, but you do not seem to actually make use of them...?

Truth be told, what I would need is wildcard support, to whitelist everything inside `lib/`. But please do not derail your logic only for my very particular use-case.

**Comment by lukehutch** [comment]
@gcristescu oops, correct, I forgot to remove those two fields. They were left over from a previous version where I separately checked those collections for whitelisted lib and ext jars. Now the checking is done in `JarUtils.isJREJar()`. Can you please set a breakpoint there and see if that method is not working correctly, and/or please attach your verbose logs? (Call `.verbose()` before `.scan()`.)

I could add wildcards, I just took a shortcut by not adding them yet, since I wasn't sure you'd need them. Are you sure there are no JDK/JRE jars in `lib/` or `jre/lib/` that you don't want to scan?

**Comment by lukehutch** [comment]
@gcristescu Oh, I see the problem with the `JarUtils.isJREJar()` method -- I should have tested this. I'm comparing a complete path to a jar name. I'll fix that, my apologies.

**Comment by gcristescu** [comment]
@lukehutch No worries.
Regarding wildcards: I am packaging the JRE within my application, so that is why I end up having a `jre/` folder (which is also `java.home`, for all intents and purposes) and a `lib/` folder beside it. However, this `lib/` folder only contains my jars, nothing from JRE - so I would want to include everything in it - and of course a wildcard would be preferable, because it would also be future-proof.

**Comment by lukehutch** [comment]
I see. Can you please verify that the logic in the static block in `JarUtils` will even find your `lib/` directory? If it is one level above `java.home`, it will not, currently. Should I also search for `lib/` in the parent directory of `java.home`? This seems a bit sketchy to do in the general case, in case the parent directory of `java.home` has nothing to do with Java. Or did you mean to say that the actual value of `java.home` includes two subdirectories, `lib/` and `jre/`? (The current code will support this.)

I just checked in some code changes that should fix things for your situation. To whitelist everything in `lib/`, you will just add `"lib:"` to your whitelist. However, wildcards (actually `*` globs) are now supported too, e.g. `"lib:jarprefix*`.  Please see if the master version works for you (I actually tested it this time :-) , and it works for me).

**Comment by lukehutch** [comment]
@gcristescu Please test version 3.1.5, hopefully it will work for you.

**Comment by gcristescu** [comment]
@lukehutch looks good. I tested `"lib:"`, `"lib:my.jar"`, `"lib:prefix*"`; it took me longer, because I had a problem with the log (with .verbose()) not being generated at all. Turned to be an out-of-memory issue on my part; obviously all this lib scanning needs to be done carefully.

Thank you for your support, and I'll just take advantage of the opportunity to tell you that this is an awesome little project - good luck with all!

**Comment by lukehutch** [comment]
@gcristeau thanks for testing, and you're welcome! I try to stay really on top of updates and bug reports / feature requests, as a way of giving back, but also partly out of frustration over the years at most bugs in most OSS bug trackers languishing and never even being touched by the developers.

I'm curious for future reference, what happens with an OOM error? Is there a silent failure? That's surprising...

**Comment by lukehutch** [comment]
Oops, ignore the last commit message, I referenced the wrong bug.
