### ISSUE TITLE
java.lang.ClassCastException in Wildfly 10

### ISSUE THREAD

**Issue by edufa** [lukehutch/fast-classpath-scanner#26]
environment: wildfly 10.0.0.CR2
Java 8
exception:
```java
java.lang.ClassCastException: org.jboss.modules.ModuleClassLoader cannot be cast to java.net.URLClassLoader
	at io.github.lukehutch.fastclasspathscanner.scanner.ClasspathFinder.parseSystemClasspath(ClasspathFinder.java:282)
	at io.github.lukehutch.fastclasspathscanner.scanner.ClasspathFinder.getUniqueClasspathElements(ClasspathFinder.java:318)
	at io.github.lukehutch.fastclasspathscanner.scanner.RecursiveScanner.scan(RecursiveScanner.java:398)
	at io.github.lukehutch.fastclasspathscanner.scanner.RecursiveScanner.scan(RecursiveScanner.java:447)
	at io.github.lukehutch.fastclasspathscanner.FastClasspathScanner.scan(FastClasspathScanner.java:1064)
```

my code

```java
		new FastClasspathScanner()  
			.matchClassesWithAnnotation(Entity.class, new ClassAnnotationMatchProcessor() {
				@Override
				public void processMatch(Class<?> matchingClass) {
		            System.out.println("Annotation Entity: " + matchingClass);
				}
			})
			.verbose()
		    .scan();		
```

**Comment by lukehutch** [comment]
Oh interesting. I was wondering if this was ever going to come up. What environment are you running in? (Straight JDK? Maven? Tomcat? What version?)

**Comment by lukehutch** [comment]
OK, I just pushed a change, can you please try the version in GitHub master, and let me know if it works? In particular, check if the output from .verbose() is listing all the paths that you think JBoss should be loading classes from.

**Comment by edufa** [comment]
thanks for the fast replay.
I try the new code, very good no exception, but dont find my classes.

Im using an external wildfly and deploying using maven.
here the .verbose() output
I have three .jar with package 'com/xyz'

```java
12:06:41,419 ERROR [stderr] (default task-3) FastClasspathScanner: Found classpath element: D:\wildfly\wildfly-9.0.1.Final\jboss-modules.jar
12:06:41,561 ERROR [stderr] (default task-3) FastClasspathScanner: *** Starting scan ***
12:06:41,561 ERROR [stderr] (default task-3) FastClasspathScanner: Classpath elements: [D:\wildfly\wildfly-9.0.1.Final\jboss-modules.jar]
12:06:41,562 ERROR [stderr] (default task-3) FastClasspathScanner: Whitelisted paths:  [com/xyz/]
12:06:41,562 ERROR [stderr] (default task-3) FastClasspathScanner: Blacklisted paths:  []
12:06:41,562 ERROR [stderr] (default task-3) FastClasspathScanner: => Scanning classpath element: D:\Wildfly\wildfly-9.0.1.Final\jboss-modules.jar
12:06:41,563 ERROR [stderr] (default task-3) FastClasspathScanner: Scanned jar D:\wildfly\wildfly-9.0.1.Final\jboss-modules.jar in 1 msec
12:06:41,566 ERROR [stderr] (default task-3) FastClasspathScanner: *** Time taken by .scan(): 149 ms ***
```

**Comment by lukehutch** [comment]
Hmm, I have no idea how to set this up, can you please send me a source
codebase for a minimal testcase, with building and running instructions?
Bonus points for instructions for running in the Eclipse debugger :)

**Comment by culmat** [comment]
I had the same issue in weblogic and the fixed proposed in https://github.com/lukehutch/fast-classpath-scanner/pull/28 works for me.
Maybe it would be worth to put this into some extension mechanism i.e. [ServiceLoader](https://docs.oracle.com/javase/6/docs/api/java/util/ServiceLoader.html) so users can plugin in their own implementations.

**Comment by lukehutch** [comment]
Hi edufa, I just checked in a new version of the JBoss ClassLoader code. It should fix your problem, at least when running locally (it works for me when running in Eclipse), but I don't know the format of URLs used by JBoss for deployment. Can you please test this and let me know if it works for you? Thanks!

**Comment by lukehutch** [comment]
Hi @edufa and @culmat -- can you please test the latest FastClasspathScanner with WildFly and WebLogic respectively?

@culmat -- thanks for the suggestion of ServiceLoader, I didn't know about that mechanism, and it was a great solution to making the classloader handling work in a pluggable way.

**Comment by lukehutch** [comment]
I'm assuming this is fixed. Please re-open if not. Thanks for the report.
