### ISSUE TITLE
cloud not using in scala

### ISSUE THREAD

**Issue by hepin1989** [lukehutch/fast-classpath-scanner#3]
I am trying to using it in scala.but it could not found any subclass
```
scanner.matchSubclassesOf(classOf[AbstractEngine],new SubclassMatchProcessor[AbstractEngine] {
  override def processMatch(matchingClass: Class[_ <: AbstractEngine]): Unit = {
    println(matchingClass)
  }
}).scan()
```
I have wrote a java class with static method to invoke the scanner
```
public class ClassScanner {
    public static void findSubClass () {
        FastClasspathScanner scanner = new FastClasspathScanner(new String[]{"qgame"})
                .matchSubclassesOf(AbstractEngine.class, System.out::println);
        scanner.scan();
    }
}

```
still nothing ,anything wrong?

**Comment by hepin1989** [comment]
close now,in fact is that it could not using with sbt.thanks.
very handy library.

**Comment by lukehutch** [comment]
So it works with Scala then? I haven't tested it with Scala. What was the problem with sbt?

**Comment by hepin1989** [comment]
yeah,it works.thanks for that.
the problem seems sbt add some prefix to the package when I start the program in sbt or in scala console or worksheet.

I used using guava.not fit ,will throw some exception
```
  def subTypeof[T](classLoader: ClassLoader, clazz: Class[T], filter: String => Boolean): Set[Class[_]] = {
    val classPath = ClassPath.from(classLoader)
    val allClasses = classPath.getAllClasses
    implicit def imutableSet2ScalaSet[V](input: ImmutableSet[V]): Set[V] = {
      val itr = input.iterator()
      var set = Set.empty[V]
      while (itr.hasNext) {
        set += itr.next()
      }
      set
    }
    allClasses.filter(classInfo => filter(classInfo.getPackageName)).map(_.load()).filter(clazz.isAssignableFrom)
  }
```

in fact ```    val allClasses = classPath.getAllClasses```,this call, guava is loading class to the class loader,not a nice way,but yours ,very handy and nice.

I found another way to doing something like this is this lib :
https://github.com/atteo/classindex

but seems like I could not run it via scalac.

anyway ,thanks very much for this handy lib

**Comment by lukehutch** [comment]
You're welcome, glad it works for you!
