### ISSUE TITLE
If no annotations found scan throws NullPointerException

### ISSUE THREAD

**Issue by rbkcapdm** [lukehutch/fast-classpath-scanner#4]
When using FastClasspathScanner.matchClassesWithAnnotation, if there are no annotations found then a NullPointerException is thrown inside the ClassMatcher class added, since classGraphBuilder.getClassesWithAnnotation() returns null rather than an empty list.

The fix is either to check if null returned, or to modify getClassesWithAnnotation to return an empty list by default.

getClassesImplementing has the same issue.

**Comment by rbkcapdm** [comment]
See proposed fix in pull request #5

**Comment by lukehutch** [comment]
Good catch, much appreciated!
