### ISSUE TITLE
Wildcard support in jar filters

### ISSUE THREAD

**Issue by drekbour** [lukehutch/fast-classpath-scanner#48]
Since I know my annotations exist only our in-house jars, I could benefit from saying:
````java
new FastClasspathScanner("org.company.product", "jar:org-company-product-*").scan()
````

**Comment by lukehutch** [comment]
This is a good suggestion, I'll try to put this into the next release. How urgent is this for your current usage? It might take me a few days to get to this, given that I just got back from traveling.

**Comment by lukehutch** [comment]
This is now implemented in git, can you please test for your usecase and let me know if it works for you?

**Comment by lukehutch** [comment]
Closing, please re-open if it doesn't work for you.
