### ISSUE TITLE
add override method which don't try to load the class in the FastClasspathScanner

### ISSUE THREAD

**Issue by hepin1989** [lukehutch/fast-classpath-scanner#6]
like this 
```
    public FastClasspathScanner matchClassesWithAnnotation(final Class<?> annotation,
            final ClassAnnotationMatchProcessor classAnnotationMatchProcessor) {
        if (!annotation.isAnnotation()) {
            throw new IllegalArgumentException("Class " + annotation.getName() + " is not an annotation");
        }
        classMatchers.add(new ClassMatcher() {
            @Override
            public void lookForMatches() {
                // For all classes with the given annotation
                for (String classWithAnnotation : classGraphBuilder.getClassesWithAnnotation(annotation.getName())) {
                    try {
                        // Load class
                        Class<?> klass = Class.forName(classWithAnnotation);

                        // Process match
                        classAnnotationMatchProcessor.processMatch(klass);

                    } catch (ClassNotFoundException | NoClassDefFoundError e) {
                        throw new RuntimeException(e);
                    }
                }
            }
        });
        return this;
    }
```
for the line here
```
                        // Load class
                        Class<?> klass = Class.forName(classWithAnnotation);
```

we may provide a new type of processor with just accept string.

with this,we may don't need to provide method which allow us to specify the classloader.

**Comment by hepin1989** [comment]
and the``` forName ```method call will cause the class been initialized ,which may no what we want

**Comment by lukehutch** [comment]
I'm all for not loading classes unless absolutely necessary. But what will you do with a class, if it's not to load it eventually? Are you saying you just want a list of strings back of matching fully-qualified class names, and then you'll decide yourself whether to load them or not?

**Comment by lukehutch** [comment]
Fixed, please see the version I just pushed. Thanks for the suggestion!

**Comment by hepin1989** [comment]
@lukehutch yes,I may want to load but don't initialized it.another issue I will check when I am free is that,currently,this library could not find the classpath,if I am using sbt or package the classpath in a classpath.jar.

**Comment by lukehutch** [comment]
Hi @hepin1989 this library should be able to scan within JAR files, but if it's not working, please narrow down the problem and open another bug. Thanks!

**Comment by hepin1989** [comment]
@lukehutch will later :),thanks too.
