### ISSUE TITLE
Version 1.90.7 is not compatible with Java 7

### ISSUE THREAD

**Issue by haschart** [lukehutch/fast-classpath-scanner#65]
First off, thank you for a wonderful Java library.  I have a project that was using Reflections, however it plus the size of the libraries it relies on was over 4 times the size of my project.  Your library works and its tiny, and its fast.   However, although the description of it says the released to Maven works with Java 7, the current version doesn't.   
The issue is primarily the use of a couple of methods that were newly added to classes for Java 8.  The use of putIfAbsent on the HashMap in ClassInfo,java is a problem.   As is the use of String.join  in ClassInfo.java.  and the java.time classes in Log.java    
The first issue can be handled by passing in a ConcurrentHashMap instead of a plain HashMap.
The java.time issue is more of a problem to fix, since the new Java 8 classes are Thread-safe whereas the java.text.SimpleDateFormat they replaced are very much not.

**Comment by lukehutch** [comment]
Oops, sorry about that. I have my JDK settings set to Java 8 so that I can still have @FunctionalInterface annotations on the MatchProcessors for those that can use them. I'll try to fix this soon.

**Comment by lukehutch** [comment]
Hi, please check version 1.91.0. The only non-JDK7 thing in that build is the `@FunctionalInterface` annotations again, and it seemed fine to leave these in the build previously (JDK7 seems to just ignore them if it doesn't know what they are).

**Comment by haschart** [comment]
I'm having trouble testing it here at work.   My development machine at work only has Java 8, however testing either of the two new jars  (version 1.91.0  or 1.91.1)  on that Java 8 machine, and the program fails with a complaint of NoSuchMethodError at the call to scan()  on a FastClassPathScanner object.
java.lang.NoSuchMethodError: io.github.lukehutch.fastclasspathscanner.FastClasspathScanner.scan()Lio/github/lukehutch/fastclasspathscanner/FastClasspathScanner;

https://github.com/solrmarc/solrmarc_the_next_generation/blob/master/src/org/solrmarc/index/utils/FastClasspathUtils.java

**Comment by lukehutch** [comment]
Hi, can you please try 1.91.4? Hopefully it is fixed now.

**Comment by haschart** [comment]
On my laptop at home running Java 7,  that version works perfectly.  Thank you so much.

**Comment by lukehutch** [comment]
Great, thanks for testing. I'll try to be more careful about this in future. Though I notice that JDK 7 has reached EOL except for customers that are paying Oracle for support, I didn't know we were already at that point -- there are a lot of JDK 7 installations out there that won't be upgraded for a long time!

Please re-open if you see any further problems. Thanks for the report!
