### ISSUE TITLE
NullPointerException when scan reaches java.lang.object

### ISSUE THREAD

**Issue by TFaga** [lukehutch/fast-classpath-scanner#7]
Hi!

I'm trying to scan every class in the class path (empty constructor - I'm building a framework so I can't know package names to scan). However since I'm using IntelliJ IDEA for development and the it includes the JRE jars in the class path when running, I get a NullPointerException when the scan reaches java.lang.Object and tries to retrieve its parent class (as Object is the only one that does not have one).

Heres the exception:

```
Caused by: java.lang.NullPointerException
	at io.github.lukehutch.fastclasspathscanner.FastClasspathScanner.readClassInfoFromClassfileHeader(FastClasspathScanner.java:828)
	at io.github.lukehutch.fastclasspathscanner.FastClasspathScanner.scanZipfile(FastClasspathScanner.java:1078)
	at io.github.lukehutch.fastclasspathscanner.FastClasspathScanner.scan(FastClasspathScanner.java:1145)
	at io.github.lukehutch.fastclasspathscanner.FastClasspathScanner.scan(FastClasspathScanner.java:1188)
```

I placed a breakpoint at the line the exception happened and read the `className` variable defined in line 818 of `FastClasspathScanner.java` which was `java.lang.Object`.

Of course when I package the app and run it from the terminal it works normally as the JRE jars are not explicitly included in the classpath. However it's still a problem since it makes development a bit problematic.

**Comment by lukehutch** [comment]
Hi, thanks for the report. The line numbers of the version checked into git are different from yours, what is the source code line throwing the NPE? Thanks!

**Comment by TFaga** [comment]
Sorry about that I forgot I edited the file a little locally.

The exception occurs here:

https://github.com/lukehutch/fast-classpath-scanner/blob/master/src/main/java/io/github/lukehutch/fastclasspathscanner/FastClasspathScanner.java#L836

And here is the `className` variable I looked at:

https://github.com/lukehutch/fast-classpath-scanner/blob/master/src/main/java/io/github/lukehutch/fastclasspathscanner/FastClasspathScanner.java#L826

Thanks! :)

**Comment by lukehutch** [comment]
Ah! I see what's going on. I couldn't see how that line was throwing an exception. java.lang.Object has a null superclass name, that makes sense. Thanks, fixed in git.

**Comment by TFaga** [comment]
Thanks again for the quick response!
