### ISSUE TITLE
Package whitelist/scanSpec not working properly as of 1.92.0 (for Manifest.mf attached jars?)

### ISSUE THREAD

**Issue by kjerk** [lukehutch/fast-classpath-scanner#73]
It seems that as of 1.92.0 there is a problem with the package scan prefix mechanism, it's unable to find any classes at all. This is a project with ~300 dependencies, so I have to use IntelliJ's dynamic classpath feature to run it properly, meaning the classpath deps are packed into a jar with a MANIFEST.MF, which is a very likely exacerbant. Switching back to 1.91.6 this is fixed.

If you remove the package whitelist from the constructor, it is able to find classes again >1.92.0 (screenshot 2).

Example screenshots:
**1.92.0 (package whitelist)** (up to current 1.93.1)
![fsc_scan_issue_1 92 0](https://cloud.githubusercontent.com/assets/2738686/17308485/1d2648a4-57ef-11e6-831c-0a8e9fca82bd.jpg)

**1.92.0 (no whitelist)**
![fsc_scan_issue_1 92 0_no_packageprefix](https://cloud.githubusercontent.com/assets/2738686/17308586/a75722dc-57ef-11e6-8530-402889929f91.jpg)

**1.91.6 (package whitelist)**
![fsc_scan_issue_1 91 6](https://cloud.githubusercontent.com/assets/2738686/17308482/191cfe2e-57ef-11e6-95a9-93222d98034f.jpg)

**Comment by lukehutch** [comment]
Hi @kjerk, thanks for the detailed report, and for narrowing down the affected versions!

Unfortunately a huge amount changed between 1.91.6 and 1.92.0, so I can't narrow down what's happening that way. However, all the unit tests are passing, so on my platform (Linux, running in either Maven or Eclipse), whitelisting is working. Are you running on Windows?

Is there anyway you can please package up a standalone minimal testcase? I have a working Windows VM to test Windows issues in, as of a couple of days ago, so I could see if I can duplicate your issue there, if you're running on Windows.

You said:

> This is a project with ~300 dependencies, so I have to use IntelliJ's dynamic classpath feature to run it properly

Are you referring to a limitation (or slowdown) in FastClasspathScanner, or IntelliJ? What do you mean by "to run it properly"?

**Comment by kjerk** [comment]
Ah this is actually a windows shell limitation, if you have many dependencies, when it attempts to execute the program it can exceed the character limitation of the shell, so it's a workaround to generate a jar with a manifest to enable arbitrary length classpath
http://stackoverflow.com/a/4853779/3838956

I thought that was a likely fly in the ointment.

I'll see if I can come up with a minimum viable project that illustrates the issue.

**Comment by lukehutch** [comment]
Interesting, I didn't know about that!

0.93.1 contained an important fix for Windows classloader-finding, but you already tested that, so that's not the problem.

Thanks, will see what I can find with your minimum viable project!

**Comment by lukehutch** [comment]
I was able to duplicate this in IntelliJ inside a Windows VM. Fixed in 1.93.2.

Good catch, thanks for reporting this, it impacts more than just running inside IntelliJ. (Turns out the way IntelliJ implements the dynamic classpath is by using a Class-Path entry in a manifest file, and I was incorrectly checking the manifest file against the whitelist before reading its contents.)

**Comment by kjerk** [comment]
Hey, that's awesome! Sorry I wasn't able to get around to trying to generate a test project until today, but it looks like you were able to do it yourself anyway in the meanwhile :relaxed: 

Thanks for the fix!

**Comment by lukehutch** [comment]
No worries, you caught a real showstopper that I had missed :)  Thanks!
