### ISSUE TITLE
FastClasspathScanner#overrideClassPath do not work correctly

### ISSUE THREAD

**Issue by DefconZhou** [lukehutch/fast-classpath-scanner#75]
### version
2.0.1
### background
I write a framework, then I put all plugin jar on specified directory. So I need FastClasspathScanner to get all class implements the plugin interface.
### issue
plugin jar directory: D:/xxx/procedure/class 
                file:xxx-procedure-auth-1.0-SNAPSHOT.jar
code: 
```
 FastClasspathScanner scanner = new FastClasspathScanner();
 scanner.overrideClasspath("D:/xxx/procedure/class/xxx-procedure-auth-1.0-SNAPSHOT.jar");
 ScanResult scanResult = scanner.matchClassesImplementing(Procedure.class, clazz -> {
            System.out.println(clazz.toString());
        }).verbose().scan();
```
output:

> 195011028-05-14T09:40+08	FastClasspathScanner	FastClasspathScanner version 2.0.1
> 195012084-03-27T20:03+08	FastClasspathScanner	Overriding classpath
> 195012131-08-18T07:06+08	FastClasspathScanner	-- Adding classpath element: D:/xxx/procedure/class/xxx-procedure-auth-1.0-SNAPSHOT.jar
> 195012861-12-29T12:50+08	FastClasspathScanner	Scanning jarfile D:\xxx\procedure\class\xxx-procedure-auth-1.0-SNAPSHOT.jar (took 0.008536 sec)
> 195013056-12-11T21:00+08	FastClasspathScanner	-- Found whitelisted file in jarfile: META-INF/MANIFEST.MF
> 195013063-06-07T16:40+08	FastClasspathScanner	-- Found whitelisted file in jarfile: com/zz/xxx/GetUserProcedure2.class
> 195013118-07-07T04:40+08	FastClasspathScanner	-- Found whitelisted file in jarfile: META-INF/maven/com.zz.xxx/xxx-procedure-auth/pom.xml
> 195013123-09-19T20:13+08	FastClasspathScanner	-- Found whitelisted file in jarfile: META-INF/maven/com.zz.xxx/xxx-procedure-auth/pom.properties
> 195013237-05-10T14:26+08	FastClasspathScanner	Classpath element order:
> 195013244-05-18T01:40+08	FastClasspathScanner	-- 0: D:\xxx\procedure\class\xxx-procedure-auth-1.0-SNAPSHOT.jar
> 195013520-11-27T20:06+08	FastClasspathScanner	Parsing classfile jar:D:\xxx\procedure\class\xxx-procedure-auth-1.0-SNAPSHOT.jar!com/zz/xxx/GetUserProcedure2.class (took 0.003717 sec)
> 195013576-11-05T18:46+08	FastClasspathScanner	-- Found class com.iflytek.xxx.GetUserProcedure2
> 195013580-02-27T15:33+08	FastClasspathScanner	---- Superclass: java.lang.Object
> 195013634-07-26T13:50+08	FastClasspathScanner	---- Interfaces: com.zz.xxx.procedure.Procedure
> 195013637-08-03T15:03+08	FastClasspathScanner	---- Annotations: com.zz.xxx.procedure.annotation.Proc
> 195013645-06-28T12:43+08	FastClasspathScanner	Building class graph (took 0.005518 sec)
> 195013864-03-15T13:30+08	FastClasspathScanner	Calling ClassMatchProcessors
> 195014035-02-08T09:46+08	FastClasspathScanner	-- Matched class implementing interface com.zz.xxx.procedure.Procedure: com.zz.xxx.GetUserProcedure2
> 195014056-06-01T16:00+08	FastClasspathScanner	Exception while calling ClassMatchProcessor: java.lang.RuntimeException: Exception while loading or initializing class com.zz.xxx.GetUserProcedure2
> 195014061-01-03T17:10+08	FastClasspathScanner	Completed scan (took 0.079989 sec)

Load or initializ class failed. Why?

**Comment by DefconZhou** [comment]
I have found the problem. FastClasspathScanner use default AppClassLoader/BootstrapClassLoader to load class,  so it can not find self defined directory class when loading  plugin class name.

![xxxxx](https://cloud.githubusercontent.com/assets/2505581/18120436/1ed93bd8-6f92-11e6-8872-26cb2f48fb7b.PNG)

**Comment by lukehutch** [comment]
Thanks for the report, and thanks for figuring out the root of the problem. Just so I understand, you manually overrode the classpath with the jar path that you passed to the scanner, but is the jarfile you listed not actually on the Java classpath? This would explain why Class.forName() doesn't work. 

If that's the case, you can add that jar to the classpath, or you can use the methods that don't actually try to instantiate the class, e.g. `ScanResult#getNamesOfClassesImplementing(Procedure.class)`

Does that work? Or is there still an issue with FastClasspathScanner?

**Comment by DefconZhou** [comment]
@lukehutch  Yes,That's the point. 
Add all plugin jars in classpath is a good way, but now I have something confused too. The framework I write support to add/remove/update plugin jar  dynamically. So I have to watch all plugin jars for loading/uninstalling/overriding plugin component in runtime, then I need a custom classloader to load all plugin class with full control and isolate plugin class from default runtime env. If I want to use FastClasspathScanner to do this,  perhaps I need to write more code based on FastClasspathScanner.

**Comment by lukehutch** [comment]
I don't understand what you mean about dynamically loading/uninstalling/overriding plugin components at runtime. It's very complicated to do this:

http://tutorials.jenkov.com/java-reflection/dynamic-class-loading-reloading.html

Is this what you mean?  Even if so, you still need a ClassLoader to do the class loading, so anytime a plugin is "loaded", Class.forName() should work.

If you want to detect classes with FastClasspathScanner and a custom classpath, but *without* loading classes, that's totally fine, you just don't use a MatchProcessor for this ("Mechanism 1"). Instead use "Mechanism 2" or "Mechanism 3". See here:

https://github.com/lukehutch/fast-classpath-scanner/wiki/1.-Usage

Neither Mechanism 2 nor Mechanism 3 tries to load the classes using a Class.forName(), and the classes don't need to be loaded using a ClassLoader either.

Does that solve your issue?

**Comment by DefconZhou** [comment]
Sorry , I have not explain all of that more clearly. 
Now I  will explain my framework action.

==================================================
Plugin Class Demo
```
public interface Plugin {
     void execute(String[] params);
}
```

Auth.jar (a plugin jar) 
```
@Plugin("auth")
public Auth implements Plugin {
     public void execute(String[] params) {
           .......................do something
     }
}

```
Step 1: Now I put auth.jar into plugin directory named A (**not in classpath** ). When I start my app,  the framework need to find all class implements of Plugin in specified directory A. Then load Auth.class and instantiate the class. Every plugin have a name, Auth.class defined by plugin annotation. Then in the memory, app get a map ("auth"-> AuthInstance). If app get a request with action name "auth", then AuthInstance call execute method.For isolation and safety , directory A is not be added in to classpath, so Class#forName can not load Auth.class, the framework have a custom classloader to load all plugin jars.

Step2: App is running, then I  put Store.jar in directory A. The framework need to watch directory A, and load added Store.class. ..... The app get map(auth->authInstance, store->storeInstance).
Store.jar (a plugin jar)
```
@Plugin("store")
 public Store implements Plugin {
      public void execute(String[] params) {
            .......................do something
      }
 }

```

Step3 Now app is running, I put Auth2.jar with the same plugin name auth in directory A.The framework need to load Auth2.class
and instantiate this and replace the AuthPlugin before. So app get a map ("auth"-> Auth2Instance, "store"->StoreInstance).

Auth2.jar (a plugin jar)

```
@Plugin("auth")
public Auth2 implements Plugin {
	
	public void execute(String[] params) {
	   ...........do something
	}

}

As above , that's what I want to do.
Two tips: 
   1. For safety and isolation, I can not put plugin jars in classpath, I only need to have a custom classloader.
   2. I need to instantiate all plugin class.

Sorry for my pool english.
That's all.

**Comment by lukehutch** [comment]
OK, then please see my previous comment. You need Mechanism 2 or Mechanism 3. You were using Mechanism 1, which is what is causing your problem. Mechanisms 2 and 3 do not require the classes to be on the classpath, and they do not require classes to be loaded to be detected.

**Comment by DefconZhou** [comment]
Now I understand what you mean. You let me use Mechanism 2 or Mechanism 3 to find class. After finding class, Load class and instantiate class are my work. Yes, that's a right way.

**Comment by lukehutch** [comment]
Correct, yes. The classloading is entirely up to you. But Mechainsms 2 and 3 were created to solve exactly this sort of problem: finding classes without even calling the ClassLoader. (You correctly identified that you will need to manually override the classpath in your case, since you are scanning jars that you don't want to be in the classpath.)

Try it out, and let me know if this works for you. (It should work.)

**Comment by lukehutch** [comment]
Hi, can you please confirm if the suggested mechanisms fix this problem for you? If so, please go ahead close the bug. Thank you!

**Comment by DefconZhou** [comment]
@lukehutch Sorry for forgetting it. Yes, as you suggested, I use Mechainsms 2 find all target class and use self defined ClassLoader to load class. It works well.

**Comment by lukehutch** [comment]
@DefconZhou great, glad it works for you. Thanks for the report, please let me know if you find any other issues.
