### ISSUE TITLE
Provide a way to pass blacklisted packages

### ISSUE THREAD

**Issue by TFaga** [lukehutch/fast-classpath-scanner#8]
I'm creating a framework that will need to scan through the users classes, which means that I cannot limit the scan to a specific package as it can be anything. This means that the library will also scan all my classes and dependencies which in my case is completely unnecessary and will only slow down startup time.

A simple solution would be to provide a list of packages to ignore the same way you can provide a list of packages to scan.

**Comment by lukehutch** [comment]
Hi, thanks for the feature request. Please test the latest checkin (both for whitelisting and blacklisting) and let me know if it works for you. Thanks!

**Comment by TFaga** [comment]
Awesome it works perfectly! Thanks for the quick response.

**Comment by lukehutch** [comment]
Great, thanks for testing!
