### ISSUE TITLE
Unblacklisting system jars does not always work

### ISSUE THREAD

**Issue by smillies** [lukehutch/fast-classpath-scanner#80]
When I run the following code, the output is nothing:

```
public static void main(String[] args) {
	ScanResult scanResult = new FastClasspathScanner("!!","java.util").scan();
	scanResult.getNamesOfAllStandardClasses().forEach(System.out::println);
	new java.util.ArrayList();
}
```
I guess that means that although `!!` is present, the system jars are not scanned. (The last line proves that at least one class from java.util is on the classpath.)

Tested with Java 1.8.0_92 under Eclipse Neon on Windows 7.

-- Sebastian

**Comment by lukehutch** [comment]
Thanks for this report. I'll take a look at this ASAP, although my responses may be delayed over the next couple of weeks.

**Comment by lukehutch** [comment]
This one's interesting -- it looks like `rt.jar` is implicitly included on the classpath by default by the JVM, and it doesn't actually appear anywhere in the actual classpath, or in any visible URLClassLoaders. I'll have to manually add it to the list of jars to be scanned if "!!" is specified.

**Comment by lukehutch** [comment]
The fix for this has been checked in, please test. Thank you!

**Comment by smillies** [comment]
Thanks, works in current 2.0.4-SNAPSHOT.

**Comment by lukehutch** [comment]
Thanks for reporting and testing!
