### ISSUE TITLE
Only jars with known extension are being scanned

### ISSUE THREAD

**Issue by fleipold** [lukehutch/fast-classpath-scanner#87]
I ran into an issue with a jar file that had no extension. This file wouldn't be scanned.

Currently the scanner uses the static method `JarUtils#isJar(name)` to determine whether a file is a jar.

It would be nice if this name matching could be configured or a more fancy mechanism (perhaps looking at the content) could be plugged in. This probably shouldn't be the default as there would be a performance overhead.

**Comment by lukehutch** [comment]
Interesting. Is this jar auto-generated somehow? Is it possible to set up a symlink to the jar with a `.jar` extension maybe?

I can't think of a simple way to make this optional -- the scan spec is already very complex, and I don't want to add more configuration methods to `FastClasspathScanner` if I can avoid it. So I think first I need to get a better understanding of how common this is, and what the possible workarounds are.

I agree that matching based on file extension is not ideal. One possible workaround would be to open each file on the classpath to see if the first two characters were `PK`, which is the case for all zipfiles. I think that would introduce minimal overhead in any operating system that properly caches file blocks (the first block of the file will have to be read twice -- once to check if it's a jar, then once by `java.util.zip` to read the zipfile index.) However, it could be more costly for jars-within-jars. Would it be reasonable to only do this for toplevel jars?

**Comment by fleipold** [comment]
Thanks for the quick feedback. The background is that I create a ["proper" executable jar](https://coderwall.com/p/ssuaxa/how-to-make-a-jar-file-linux-executable) that starts with shell script along these lines:

~~~ .bash
#!/bin/bash

if [ -n "$JAVA_HOME" ]; then
    JAVA_COMMAND=${JAVA_HOME}/bin/java
else
    JAVA_COMMAND=`which java`
    if [ $? -ne 0]; then
        echo "No java found on path."1>&2
        exit 1
    fi
fi

exec $JAVA_COMMAND -jar $0 "$@"
~~~

Dropping the extension was more about aesthetics. Also, this kind of thing breaks the simple approach of checking for the PK in the beginning of the file. Only checking top-level jars would be fine for my use case.

I have to admit that my motivation is purely aesthetic and worked around the problem by actually renaming the file to ".jar".

**Comment by lukehutch** [comment]
I agree with the aesthetics reasons, and actually using a .jar extension is not the best solution, because this is not in fact a .jar file.

It's actually quite surprising that what you're doing works at all! `java -jar` must scan through the file looking for a `PK` marker or something. This should not work at all :-)  BTW it looks like you're missing an `exit` statement after the `exec` line.

I suggest modifying the script to use a binary payload mechanism like the one linked from the link you shared, then write the binary payload out to a `.jar` file in a temporary directory, then call `java -jar` on the temporary file, removing it when `java` returns.

**Comment by fleipold** [comment]
The pk spec allows random data before the block marker - at least it doesn't prohibit it - and most  unzip implementations will be fine with that  ;-).

The `exit` statement is not required, because the [`exec`](https://linux.die.net/man/3/exec) call replaces the current process with the java process (i.e. the original bash process that ran the script morphed into a java process) - unix power/ weirdness. 

I like the temp file approach. Thanks a lot!

**Comment by lukehutch** [comment]
Thanks, both those points in your last comment are good info to know. Thanks for the bug report!
