### ISSUE TITLE
Exception handling in annotation match processor

### ISSUE THREAD

**Issue by fleipold** [lukehutch/fast-classpath-scanner#88]
If an exception is is thrown in the match process callback the scanner seems to stop scanning, but doesn't indicate the problem. I also couldn't find a method on the `ScanResult` that would indicate that there was a problem.

The best solution in my view would be to throw an exception from the scan method if anything goes wrong. Here  are two test cases that illustrate the problem:

~~~ .java
    @Test
    public void exceptionsArePropagated() {

        try {
            FastClasspathScanner scanner = new FastClasspathScanner();

            scanner.matchClassesWithMethodAnnotation(Test.class, (clazz, method) -> {
                throw new RuntimeException("Wham!");
            });

            scanner.scan();

            fail("Would have expected to get an exception here");
        } catch (Exception e) {
            assertEquals("Wham!", e.getMessage()); // Arguably the exception could also be wrapped.
        }
    }

    @Test
    public void exceptionsAreProperlyIgnored() {
        FastClasspathScanner scanner = new FastClasspathScanner();

        final AtomicInteger callCounter = new AtomicInteger(0);

        scanner.matchClassesWithMethodAnnotation(Test.class, (clazz, method) -> {
            callCounter.incrementAndGet();
            throw new RuntimeException("Wham!");
        });

        scanner.scan();

        int numberOfCalls = callCounter.get();
        assertTrue("There @Test are two annotations in this class alone.", numberOfCalls > 1);
    }
~~~

**Comment by lukehutch** [comment]
Try calling `.verbose()` before `.scan()`. Is the exception logged, at least?

FastClasspathScanner intentionally keeps scanning if exceptions are thrown (e.g. in the case of IOExceptions), but you raise a good point that exceptions in user code should be re-thrown to the caller.

It's a little more complicated by the fact that scanning is asynchronous, but the user exception could be wrapped in an ExecutionException for the async call, or a RuntimeException for the synchronous call.

**Comment by fleipold** [comment]
If I run with `.verbose()` I do get this line - as one of many:

~~~
2016-10-12T18:05:42.798-0400	FastClasspathScanner	Exception while calling ClassMatchProcessor: java.lang.RuntimeException: Wham!
~~~
However, I think the second test shows that it does indeed **not** continue scanning. I find that surprising.

Generally I prefer exceptions not to be swallowed silently. One possible way of dealing with the problem would be to collect errors would be to collect them during the scan and then throw an exception that has a list of all the wrapped exceptions. That way you can continue the scan and still provide adequate feedback. 

On the other hand, if you think that's too much hassle, you might also just count whether there are any exceptions and throw an exceptions that says at least one callback has failed.

Which way do you think the interface should go?

**Comment by lukehutch** [comment]
I agree that swallowing exceptions silently is the wrong thing to do in this context. (The other exceptions thrown within FCS itself are all triggered by IO issues, so those are swallowed intentionally, and they're in the log if anyone needs them.)

I think it's fine to throw a single exception and stop scanning if any MatchProcessor throws an exception.

You're right that the second test should have found two annotations. I'll look into this.

**Comment by fleipold** [comment]
I happened to look a bit into the code. The problem is that the exception is not caught in ScanSpec.java:984ff:

~~~ .java
public void lookForMatches(final ScanResult scanResult, final LogNode log) {
                final String annotationName = getAnnotationName(annotation);
                for (final String classWithAnnotation : scanResult
                        .getNamesOfClassesWithAnnotation(annotationName)) {
                    if (log != null) {
                        log.log("Matched class with annotation " + annotationName + ": " + classWithAnnotation);
                    }
                    // Call classloader
                    final Class<?> cls = loadClass(classWithAnnotation);
                    // Process match
                    classAnnotationMatchProcessor.processMatch(cls);
                }
~~~
So this loop terminates upon the exception and the exception is then silently swallowed in ScanSpec.java:430ff:

~~~ .java
if (classMatchers != null) {
            for (final ClassMatcher classMatcher : classMatchers) {
                try {
                    classMatcher.lookForMatches(scanResult, //
                            log == null ? null : log.log("Calling ClassMatchProcessors"));
                } catch (final Throwable e) {
                    if (log != null) {
                        log.log("Exception while calling ClassMatchProcessor: " + e);
                    }
                }
                interruptionChecker.check();
     }
~~~
`callMatchProcessors` is the last step in the scan and to my understanding it's all sequential, so you could just collect the exception. The least thing one could do is add a `try-catch` in with a log in the loop in the first snippet. I can try to send you a pull request with the unit tests and an attempt at a solution.

**Comment by lukehutch** [comment]
Thanks for looking into this. I started working on a solution tonight but didn't finish it yet. I created a MatchProcessorException that contains a List<Exception>, and the idea was to collect exceptions in ScanResult in the way you suggest. Since I didn't get very far yet with the patch, feel free to send me a PR if you're feeling motivated, otherwise I can finish this off later. :-)

**Comment by lukehutch** [comment]
@fleipold Please test the latest commit in master, I think it does what you want.

**Comment by lukehutch** [comment]
@fleipold did you have a chance to test this and/or look at the commit yet? Thanks!

**Comment by lukehutch** [comment]
Released in version 2.0.5 -- please re-open if this doesn't work for you. Thanks for this report, this was an important bugfix / behavioral change!

**Comment by spontaliku-softaria** [comment]
It doesn't worked for me: I had infinite recursion in match processor and StackOverflowError was thrown. It was caught in ScanSpec.callMatchProcessors, but ScanResult.getMatchProcessorExceptions returned empty list.
I'm not doing athything but collecting of classes in match processor now, but it was confusing anyway.

**Comment by lukehutch** [comment]
@spontaliku-softaria ugh, that's not good! Do you have a reliable way of duplicating that problem?

**Comment by lukehutch** [comment]
@spontaliku-softaria please call `.verbose()` before calling `.scan()` so you can see the exceptions, and let me know what you find. I'll look at `ScanResult.getMatchProcessorExceptions`.

**Comment by lukehutch** [comment]
@spontaliku-softaria I checked, and `ScanResult.getMatchProcessorExceptions` does work for me. I don't see an infinite loop either.

To debug further, I will need either a minimum testcase, or the verbose logging output. The debug output is not printed until the end of scanning, so it may actually not be printed at all, since you're stuck in an infinite loop. If you are able and willing to run in a debugger, what you need to do is the following:

1. Call `.verbose()` before calling `.scan()`.
2. While running, pause the running program in the debugger (try the following steps a few times to see if the logs get significantly longer with time).
3. Find the thread that has a stackframe entry for `io.github.lukehutch.fastclasspathscanner.scanner.Scanner#call()`.
4. Get the debugger to call the `toString()` method of the `log` field of that `Scanner` object instance.
5. Paste the log output here if it's short, or a link to a Google Doc or something if it's long.

Thank you!

**Comment by lukehutch** [comment]
@spontaliku-softaria Ah, pardon the earlier comments I left here, I totally misunderstood the problem. I think you mean that your own code had an infinite loop, not that there was an infinite loop in FCS. I'll try to duplicate that.

**Comment by spontaliku-softaria** [comment]
@lukehutch Yes, my code had infinite loop.

**Comment by lukehutch** [comment]
@spontaliku-softaria Thank you, I was catching `Exceptions` but not `Errors`. Now I'm catching all `Throwables`. Fixed in 2.0.6.

**Comment by spontaliku-softaria** [comment]
@lukehutch Thank you for quick response.

**Comment by fleipold** [comment]
@lukehutch Thanks very much for the swift fix. I have updated my dependency and it works like a charm, sorry about the late feedback.

**Comment by lukehutch** [comment]
@fleipold you're welcome, this was an important fix! Thanks for reporting the bug. 2.0.7 is out now with a couple of small bugfixes too.

**Comment by lukehutch** [comment]
PS thanks for confirming it works for you too.
