### ISSUE TITLE
Match annotations with RetentionPolicy.CLASS retention policy

### ISSUE THREAD

**Issue by lukehutch** [lukehutch/fast-classpath-scanner#93]
Currently FCS only matches RuntimeVisibleAnnotations, also need to match RuntimeInvisibleAnnotations.

**Comment by lukehutch** [comment]
Released in 2.0.8.

**Comment by natros** [comment]
Wow!

You're very fast and helpful. I am astonished!

Thank you.

👏

**Comment by lukehutch** [comment]
@natros You're welcome, this is the only way that open source can work! People like you make great suggestions and contributions, and I try to remain as responsive as possible. :-)
