### ISSUE TITLE
support scala annontion?

### ISSUE THREAD

**Issue by melin** [lukehutch/fast-classpath-scanner#96]
support scala annontion?

**Comment by lukehutch** [comment]
How do Scala annotations differ from Java annotations? I think Scala just uses the regular Java annotation system, albeit in a different way? If so, these should work already.

If this doesn't work already, can you please provide a git repo with a minimal Maven project that shows an example of a Scala annotation that is not picked up by FastClasspathScanner? I don't have much Scala experience, so this would be helpful.

**Comment by lukehutch** [comment]
Closing due to lack of response. If Scala annotations are not compatible with FastClasspathScanner, please open another bug. Thank you!
