### ISSUE TITLE
Limit scan to one particular jar?

### ISSUE THREAD

**Issue by jaredjstewart** [lukehutch/fast-classpath-scanner#97]
Is there a way to scan one particular jar (or one particular classloader) rather than the whole classpath?  I'd really like to use this project to find all of the classes in one particular jar (not the whole classpath) that implement a given interface.  Also, the jar is being provided by a user, so I don't know what packages will be contained in the jar.

**Comment by jaredjstewart** [comment]
Sorry, just found https://github.com/lukehutch/fast-classpath-scanner/wiki/2.-Constructor#limiting-scanning-to-specific-jars.  Closing this issue.

**Comment by lukehutch** [comment]
Yes, that's the correct method. Let me know if it doesn't work for you.

As a simpler alternative for your particular usecase, you can also manually override the classpath with the complete path of the jar, and then perform an exhaustive scan:

https://github.com/lukehutch/fast-classpath-scanner/wiki/1.-Usage#manually-overriding-the-classpath
