### ISSUE TITLE
Whitelisting nested JARs fails due prefix FastClasspathScanner-7396178027911845861

### ISSUE THREAD

**Issue by michaldo** [lukehutch/fast-classpath-scanner#99]
If I have nested JAR x.jar, whitelisting JAR "x.jar" fails because temporaty extracted JAR is named "FastClasspathScanner-7396178027911845861-x.jar"
It is more natural whitelist by original name, not temporal name.
Workaround is whitelist with glob ('*')

**Comment by lukehutch** [comment]
This is fixed, thanks for the report. The fix is a little hacky -- I used "---" as the separator between the temp file name prefix and the original jar name (so you can't have "---" in your jar names, although this hopefully will never pose a problem in any realistic scenario).
